services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU10-ubuntu-22.04
    restart: always
    hostname: mssqldocker
    container_name: mssql
    volumes:
    # 宿主机需要 sudo chmod 777 -R data
    - type: bind
      source: ./data
      target: /var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_COLLATION: Chinese_PRC_CI_AS
      MSSQL_SA_PASSWORD: mssql.666
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: true
      TZ: Asia/Shanghai
    ports:
      - "1433:1433"
