version: "3.2"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    restart: always
    hostname: mssqllinux
    container_name: mssql
    volumes:
    # - type: volume
    #   source: mssql
    #   target: /var/opt/mssql
    #   volume:
    #     nocopy: true
    #     volumes:
    - type: bind
      # 宿主机 需要 sudo chmod 777 -R
      source: ./mount
      # 容器
      target: /var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_COLLATION: Chinese_PRC_CI_AS
      MSSQL_SA_PASSWORD: superEdwin666
      TZ: Asia/Shanghai
    ports:
      - "1433:1433"


