version: "3"

services:
  web:
    image: nginx:1.25.5
    restart: always
    container_name: nginx
    volumes:
    - type: bind
      source: ./conf.d
      target: /etc/nginx/conf.d
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
