services:
  mysql:
    image: mysql:8.0.35
    restart: always
    hostname: mysqldocker
    container_name: mysql
    volumes:
    - type: bind
      source: ./data
      target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql666
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
