services:
  redis:
    image: redis:7.2.3
    restart: always
    container_name: redis
    volumes:
    - type: bind
      source: ./data
      target: /data
    ports:
    - "6379:6379"  
    entrypoint: ["redis-server", "--requirepass", "redis666", "--save", "60 1", "--loglevel", "warning"]