version: "3.2"

services:
  redis:
    image: redis:6.2.6
    restart: always
    container_name: redis
    volumes:
    - type: volume
      source: redis
      target: /data
      volume:
        nocopy: true
    ports:
    - "6379:6379"  
    entrypoint: ["redis-server", "--requirepass", "redis", "--appendonly", "yes"]

volumes:
  redis: